// API 라우터 등록 — 모든 라우트를 /api 하위에 마운트

import { Router } from 'express';
import { healthRouter } from './routes/health.routes.js';
import { authRouter } from './routes/auth.routes.js';
import { farmRouter } from './routes/farm.routes.js';
import { animalRouter } from './routes/animal.routes.js';
import { sensorRouter } from './routes/sensor.routes.js';
import { predictionRouter } from './routes/prediction.routes.js';
import { alertRouter } from './routes/alert.routes.js';
import { feedbackRouter } from './routes/feedback.routes.js';
import { dashboardRouter } from './routes/dashboard.routes.js';
import { chatRouter } from './routes/chat.routes.js';
import { regionalRouter } from './routes/regional.routes.js';
import { actionRouter } from './routes/action.routes.js';
import { exportRouter } from './routes/export.routes.js';
import { userRouter } from './routes/user.routes.js';
import { searchRouter } from './routes/search.routes.js';
import { prescriptionRouter } from './routes/prescription.routes.js';
import { vaccineRouter } from './routes/vaccine.routes.js';
import { eventRouter } from './routes/event.routes.js';
import { economicsRouter } from './routes/economics.routes.js';
import { calvingRouter } from './routes/calving.routes.js';
import { escalationRouter } from './routes/escalation.routes.js';
import { notificationRouter } from './routes/notification.routes.js';
import { lactationRouter } from './routes/lactation.routes.js';
import { breedingRouter } from './routes/breeding.routes.js';
import { aiPerformanceRouter } from './routes/ai-performance.routes.js';
import { unifiedDashboardRouter } from './routes/unified-dashboard.routes.js';
import { publicStatsRouter } from './routes/public-stats.routes.js';
import { epidemicRouter } from './routes/epidemic.routes.js';
import { epidemicIntelligenceRouter } from './routes/epidemic-intelligence.routes.js';
import { vitalMonitorRouter } from './routes/vital-monitor.routes.js';
import { labelChatRouter } from './routes/label-chat.routes.js';
import { reportRouter } from './routes/report.routes.js';
import { weatherRouter } from './routes/weather.routes.js';
import { errorLogRouter } from './routes/error-log.routes.js';
import { herdGroupRouter } from './routes/herd-group.routes.js';
import { dryOffRouter } from './routes/dry-off.routes.js';
import { earlyDetectionRouter } from './routes/early-detection.routes.js';
import { epidemiologyRouter } from './routes/epidemiology.routes.js';
import { quarantineDashboardRouter } from './routes/quarantine-dashboard.routes.js';
import { investigationRouter } from './routes/investigation.routes.js';
import { quarantineActionRouter } from './routes/quarantine-action.routes.js';
import { kahisReportRouter } from './routes/kahis-report.routes.js';
import { smaxtecNotesRouter } from './routes/smaxtec-notes.routes.js';
import { adminRouter } from './routes/admin.routes.js';
import { earTagScanRouter } from './routes/ear-tag-scan.routes.js';
import { weightRouter } from './routes/weight.routes.js';
import { sovereignAlarmRouter } from './routes/sovereign-alarm.routes.js';
import { animalEventsRouter } from './routes/animal-events.routes.js';
import { newsRouter } from './routes/news.routes.js';
import { reportGenerateRouter } from './routes/report-generate.routes.js';
import { xaiRouter } from './routes/xai.routes.js';
import { paymentRouter } from './routes/payment.routes.js';
import { treatmentsRouter } from './routes/treatments.routes.js';

export function createApiRouter(): Router {
  const api = Router();

  // 공개 API (인증 불필요 — 로그인 전 히어로 섹션용)
  api.use('/public', publicStatsRouter);

  api.use('/health', healthRouter);
  api.use('/auth', authRouter);
  api.use('/farms', farmRouter);
  api.use('/animals', animalRouter);
  api.use('/sensors', sensorRouter);
  api.use('/predictions', predictionRouter);
  api.use('/alerts', alertRouter);
  api.use('/feedback', feedbackRouter);
  api.use('/dashboard', dashboardRouter);
  api.use('/chat', chatRouter);
  api.use('/regional', regionalRouter);
  api.use('/actions', actionRouter);
  api.use('/export', exportRouter);
  api.use('/users', userRouter);
  api.use('/search', searchRouter);
  api.use('/prescriptions', prescriptionRouter);
  api.use('/vaccines', vaccineRouter);
  api.use('/events', eventRouter);
  api.use('/economics', economicsRouter);
  api.use('/calving', calvingRouter);
  api.use('/escalation', escalationRouter);
  api.use('/notifications', notificationRouter);
  api.use('/lactation', lactationRouter);
  api.use('/breeding', breedingRouter);
  api.use('/ai', aiPerformanceRouter);
  api.use('/unified-dashboard', unifiedDashboardRouter);
  api.use('/epidemic', epidemicRouter);
  api.use('/epidemic-intelligence', epidemicIntelligenceRouter);
  api.use('/vital-monitor', vitalMonitorRouter);
  api.use('/label-chat', labelChatRouter);
  api.use('/reports', reportRouter);
  api.use('/weather', weatherRouter);
  api.use('/errors', errorLogRouter);
  api.use('/herd-groups', herdGroupRouter);
  api.use('/dry-off', dryOffRouter);
  api.use('/early-detection', earlyDetectionRouter);
  api.use('/epidemiology', epidemiologyRouter);
  api.use('/quarantine', quarantineDashboardRouter);
  api.use('/investigation', investigationRouter);
  api.use('/quarantine-action', quarantineActionRouter);
  api.use('/kahis-report', kahisReportRouter);
  api.use('/smaxtec-notes', smaxtecNotesRouter);
  api.use('/admin', adminRouter);
  api.use('/ear-tag-scan', earTagScanRouter);
  api.use('/weight', weightRouter);
  api.use('/sovereign-alarms', sovereignAlarmRouter);
  api.use('/animal-events', animalEventsRouter);
  api.use('/news', newsRouter);
  api.use('/report-generate', reportGenerateRouter);
  api.use('/xai', xaiRouter);
  api.use('/payments', paymentRouter);
  api.use('/treatments', treatmentsRouter);

  return api;
}
